infra-ci-cd.yml

diff --git a/.github/workflows/infra-ci-cd.yml b/.github/workflows/infra-ci-cd.yml
--- a/.github/workflows/infra-ci-cd.yml
+++ b/.github/workflows/infra-ci-cd.yml
@@ -55,17 +55,35 @@ jobs:
 
   terraform-plan:
     runs-on: ubuntu-latest
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.5.0
+
       - name: Terraform Init
         run: terraform init
+
       - name: Terraform Plan
-        run: terraform plan
+        id: tf-plan
+        run: |
+          exitcode=0
+          terraform plan -detailed-exitcode -no-color -out=tfplan || exitcode=$?
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          if [ $exitcode -eq 1 ]; then
+            echo "Terraform Plan Failed!"
+            exit 1
+          fi
+          - name: Upload Plan File
+          uses: actions/upload-artifact@v4
+          with:
+            name: tf-app.plan
+            path: tf-app.plan
 
   # This will only run if the terraform plan has changes, and when the PR is approved and merged to main.
   terraform-apply:
